### ISSUE TITLE
RAM usage on big repositories

### ISSUE THREAD

**Issue by ecksun** [attic/merge#4]
During the last week I ran a test backup up a big repository in order to try to
reproduce https://github.com/jborg/attic/issues/264.

The backup took 5 days and 14 hours before it failed because of excessive
memory usage (more info here:
https://github.com/jborg/attic/issues/102#issuecomment-95358735). I thought I
had 12-14 GB RAM free (16GB in total, I killed a bunch of VMs before the test)
however time claims the maximum resident set size was 10GB

This issue is about reducing memory usage of attic on large repositories.

Some statistics:

```
$ du -chs $FOLDERS
8.2T    total
$ find $FOLDERS -type f | wc -l
130579
```

The machine this was running on was a Core i7-2600k with 16 GB of RAM.

```
$ /usr/bin/time -v attic create --stats --progress /mnt/attic/bigfiles::first $FOLDERS
hashindex: malloc failed  6.54 TB D vhs/film1-04.wav
Traceback (most recent call last):
  File "/home/ecksun/tmp/attic/env/bin/attic", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ecksun/tmp/attic/scripts/attic", line 3, in <module>
    main()
  File "/home/ecksun/tmp/attic/attic/archiver.py", line 857, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/home/ecksun/tmp/attic/attic/archiver.py", line 847, in run
    return args.func(args)
  File "/home/ecksun/tmp/attic/attic/archiver.py", line 139, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/home/ecksun/tmp/attic/attic/archiver.py", line 191, in _process
    entry_path, restrict_dev)
  File "/home/ecksun/tmp/attic/attic/archiver.py", line 176, in _process
    status = archive.process_file(path, st, cache)
  File "/home/ecksun/tmp/attic/attic/archive.py", line 480, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/home/ecksun/tmp/attic/attic/cache.py", line 241, in add_chunk
    self.repository.put(id, data, wait=False)
  File "/home/ecksun/tmp/attic/attic/repository.py", line 374, in put
    self.index[id] = segment, offset
  File "attic/hashindex.pyx", line 107, in attic.hashindex.NSIndex.__setitem__ (attic/hashindex.c:2398)
Exception: hashindex_set failed
Command exited with non-zero status 1
        Command being timed: "attic create --stats --progress /mnt/attic/bigfiles::first $FOLDERS"
        User time (seconds): 72227.91
        System time (seconds): 23867.24
        Percent of CPU this job got: 19%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 134:24:57
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 10016716
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 11226
        Minor (reclaiming a frame) page faults: 733941351
        Voluntary context switches: 90803001
        Involuntary context switches: 10246595
        Swaps: 0
        File system inputs: 22191199344
        File system outputs: 35098808264
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

**Comment by anarcat** [comment]
thanks for the report, that's really interesting! out of curiosity: why didn't you file this in the upstream bugtracker?

**Comment by ecksun** [comment]
Because I ran the tests whit this repository basically. Evey though this was slow the upstream verion was at least 4x [https://github.com/jborg/attic/issues/102#issuecomment-95358735](slower).

My understanding is that the upstream version would use at least as much memory, but the test is infeasable to do with it.

**Comment by ThomasWaldmann** [comment]
@ecksun the link in your last comment doesn't work. @anarcat yes, upstream attic has same issue.

so, this issue was seen with code from here, but is not specific to the code here...

**Comment by ThomasWaldmann** [comment]
See also: https://github.com/jborg/attic/issues/302

**Comment by ecksun** [comment]
@ThomasWaldmann Oh, mixed up the [] and () in the link, I have updated it now.

**Comment by ThomasWaldmann** [comment]
as attic and borgbackup issues are tracked elsewhere meanwhile, I am closing this here.
